### ISSUE TITLE
Ensure that no secrets are in code for any of the projects

### ISSUE THREAD

**Issue by dertinfo** [dertinfo/dertinfo#13]
We're going to address this in a number of ways.

1) We're going to rotate all the secrets in the staging environment.
2) Validate that staging is still functional after the rotations
3) Repeat in Live
4) Validate Live
5) Enable secret protections through git hub via secrets scanning and push protection

**Comment by davidsmonkeys** [comment]
We've completed a secrets rotation for both the live and test environment and we've added static analysis to the repositories to scan and check for secret exposure. We've also applied this to PRs for all repositories
