### ISSUE TITLE
dertinfo-app Update so that the output is dist and alsins with the web project

### ISSUE THREAD

**Issue by dertinfo** [dertinfo/dertinfo#9]
The App project produces it's output in a folder of www and not dist. THis results in there requiring ever so slight changes to the Docker File and other build artefacts. 

Alignment would  just make things a bit easier to understand and less error prone when working cross projects

Tis is caused by in the angular.json the output path is defined as "www"

![Image](https://github.com/user-attachments/assets/a62a05dc-ab19-4f17-aa8e-e379cae41a4c)

Which then means that anything that uses this also needs to look there. THis should be "dist" to align with the web project. 

Pipelines & docker files will need updating to accommodate this change

**Comment by davidsmonkeys** [comment]
We've done this as part of the changes in making the application work in codespaces. You can see the changes in the PRs https://github.com/dertinfo/dertinfo-app/pull/16 and https://github.com/dertinfo/dertinfo-app/pull/14
